<a href="https://colab.research.google.com/github/hiraasif854-eng/python-project/blob/main/Pandas_Practice_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Name = Hira Asif
# Roll number = 898414

In [1]:
# Task 1:
# Create this student Dataframe:
import pandas as pd
data = {
    "Name" : ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks" : [70, 85, 60, 95, 45]
}
df = pd.DataFrame(data)
Marks = df["Marks"]
print(Marks.mean())
print(Marks.max())
print(Marks.min())
print(len(df))

71.0
95
45
5

In [ ]:
# Task 2:
import pandas as pd
data = {
    "Name" : ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks" : [70, 85, 60, 95, 45]
}
df = pd.DataFrame(data)
print(df[df["Marks"] >= 50])
print(df[df["Marks"] < 50])

     Name  Marks
0     Ali     70
1    Sara     85
2   Ahmed     60
3  Ayesha     95
   Name  Marks
4  Zain     45

In [ ]:
# Task 3:
import pandas as pd
data = {
    "Name" : ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks" : [70, 85, 60, 95, 45]
}
df = pd.DataFrame(data)
df["City"] = ["Karachi", "Islamabad", "Karachi", "Multan", "Lahore"]
karachi_students = df[df["City"] == "Karachi"]
print(karachi_students)

    Name  Marks     City
0    Ali     70  Karachi
2  Ahmed     60  Karachi

In [ ]:
# Task 4:
data = {
    "Name": ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Course": ["AI", "Web", "AI", "Web", "AI"],
    "Marks": [80, 90, 70, 85, 75]
}

df = pd.DataFrame(data)
result = df.groupby("Course")["Marks"].mean()

print(result)

Course
AI     75.0
Web    87.5
Name: Marks, dtype: float64

In [ ]:
# Task 5:
data = {
    "Name" : ["Ali", "Sara", "Ahmed", "Ayesha", "Zain"],
    "Marks" : [80, None, 70, None, 90]
}
df = pd.DataFrame(data)
missing_values = df["Marks"].isnull().sum()
print(missing_values)
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())
print("\nCleaned DataFrame:")
print(df)

2

Cleaned DataFrame:
     Name  Marks
0     Ali   80.0
1    Sara   80.0
2   Ahmed   70.0
3  Ayesha   80.0
4    Zain   90.0

In [ ]:
import pandas as pd
df = pd.read_csv("/content/supermarket.csv")
print(df)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2017-152156  08/11/2017  11/11/2017    Second Class
1          2  CA-2017-152156  08/11/2017  11/11/2017    Second Class
2          3  CA-2017-138688  12/06/2017  16/06/2017    Second Class
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class
4          5  US-2016-108966  11/10/2016  18/10/2016  Standard Class
...      ...             ...         ...         ...             ...
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo

           State  Postal Code   Region       Product ID         Category  \
0       Kentucky      42420.0    South  FUR-BO-10001798        Furniture
1       Kentucky      42420.0    South  FUR-CH-10000454        Furniture
2     California      90036.0     West  OFF-LA-10000240  Office Supplies
3        Florida      33311.0    South  FUR-TA-10000577        Furniture
4        Florida      33311.0    South  OFF-ST-10000760  Office Supplies
...          ...          ...      ...              ...              ...
9795    Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies
9796        Ohio      43615.0     East  OFF-AR-10001374  Office Supplies
9797        Ohio      43615.0     East  TEC-PH-10004977       Technology
9798        Ohio      43615.0     East  TEC-PH-10000912       Technology
9799        Ohio      43615.0     East  TEC-AC-10000487       Technology

     Sub-Category                                       Product Name     Sales
0       Bookcases                  Bush Somerset Collection Bookcase  261.9600
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2          Labels  Self-Adhesive Address Labels for Typewriters b...   14.6200
3          Tables      Bretford CR4500 Series Slim Rectangular Table  957.5775
4         Storage                     Eldon Fold 'N Roll Cart System   22.3680
...           ...                                                ...       ...
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.7980
9796          Art           BIC Brite Liner Highlighters, Chisel Tip   10.3680
9797       Phones                                        GE 30524EE4  235.1880
9798       Phones           Anker 24W Portable Micro USB Car Charger   26.3760
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive   10.3840

[9800 rows x 18 columns]

In [ ]:
# Viewing Data:
print(df.head(5))

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales
0                  Bush Somerset Collection Bookcase  261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2  Self-Adhesive Address Labels for Typewriters b...   14.6200
3      Bretford CR4500 Series Slim Rectangular Table  957.5775
4                     Eldon Fold 'N Roll Cart System   22.3680

In [ ]:
print(df.tail(4))

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country    City State  \
9796    CS-12490  Cindy Schnelling  Corporate  United States  Toledo  Ohio
9797    CS-12490  Cindy Schnelling  Corporate  United States  Toledo  Ohio
9798    CS-12490  Cindy Schnelling  Corporate  United States  Toledo  Ohio
9799    CS-12490  Cindy Schnelling  Corporate  United States  Toledo  Ohio

      Postal Code Region       Product ID         Category Sub-Category  \
9796      43615.0   East  OFF-AR-10001374  Office Supplies          Art
9797      43615.0   East  TEC-PH-10004977       Technology       Phones
9798      43615.0   East  TEC-PH-10000912       Technology       Phones
9799      43615.0   East  TEC-AC-10000487       Technology  Accessories

                                  Product Name    Sales
9796  BIC Brite Liner Highlighters, Chisel Tip   10.368
9797                               GE 30524EE4  235.188
9798  Anker 24W Portable Micro USB Car Charger   26.376
9799       SanDisk Cruzer 4 GB USB Flash Drive   10.384

In [ ]:
# Shape and basic properties:
print(df.shape)
print(df.columns)

(9800, 18)
Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

In [ ]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code      float64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
dtype: object

In [ ]:
# DataFrame Information:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [ ]:
print(df.describe())

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [ ]:
# Selecting Columns:
df[["Customer Name", "Segment"]]

         Customer Name    Segment
0          Claire Gute   Consumer
1          Claire Gute   Consumer
2      Darrin Van Huff  Corporate
3       Sean O'Donnell   Consumer
4       Sean O'Donnell   Consumer
...                ...        ...
9795     Sally Hughsby  Corporate
9796  Cindy Schnelling  Corporate
9797  Cindy Schnelling  Corporate
9798  Cindy Schnelling  Corporate
9799  Cindy Schnelling  Corporate

[9800 rows x 2 columns]

In [ ]:
# Selecting Rows — loc and iloc
print(df.loc[1])

Row ID                                                           2
Order ID                                            CA-2017-152156
Order Date                                              08/11/2017
Ship Date                                               11/11/2017
Ship Mode                                             Second Class
Customer ID                                               CG-12520
Customer Name                                          Claire Gute
Segment                                                   Consumer
Country                                              United States
City                                                     Henderson
State                                                     Kentucky
Postal Code                                                42420.0
Region                                                       South
Product ID                                         FUR-CH-10000454
Category                                                 Furniture
Sub-Category                                                Chairs
Product Name     Hon Deluxe Fabric Upholstered Stacking Chairs,...
Sales                                                       731.94
Name: 1, dtype: object

In [ ]:
print(df.iloc[2,4])

Second Class

In [ ]:
# Filtering Data:
filtering = df[df["City"] == "Henderson"]
print(filtering)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2017-152156  08/11/2017  11/11/2017    Second Class
1          2  CA-2017-152156  08/11/2017  11/11/2017    Second Class
538      539  CA-2016-134894  07/12/2016  11/12/2016  Standard Class
539      540  CA-2016-134894  07/12/2016  11/12/2016  Standard Class
996      997  CA-2016-162537  28/10/2016  03/11/2016  Standard Class
997      998  CA-2016-162537  28/10/2016  03/11/2016  Standard Class
998      999  CA-2016-162537  28/10/2016  03/11/2016  Standard Class
999     1000  CA-2016-162537  28/10/2016  03/11/2016  Standard Class
1866    1867  CA-2018-118857  15/04/2018  18/04/2018     First Class
2321    2322  CA-2016-109470  31/12/2016  03/01/2017    Second Class
2322    2323  CA-2016-109470  31/12/2016  03/01/2017    Second Class
2323    2324  CA-2016-109470  31/12/2016  03/01/2017    Second Class
2324    2325  CA-2016-109470  31/12/2016  03/01/2017    Second Class
2551    2552  CA-2018-101042  19/11/2018  23/11/2018  Standard Class
2552    2553  CA-2018-101042  19/11/2018  23/11/2018  Standard Class
3088    3089  US-2018-159205  31/03/2018  02/04/2018    Second Class
3089    3090  US-2018-159205  31/03/2018  02/04/2018    Second Class
3537    3538  CA-2015-158771  09/05/2015  09/05/2015        Same Day
3538    3539  CA-2015-158771  09/05/2015  09/05/2015        Same Day
3539    3540  CA-2015-158771  09/05/2015  09/05/2015        Same Day
3540    3541  CA-2015-158771  09/05/2015  09/05/2015        Same Day
4378    4379  CA-2016-140830  30/11/2016  02/12/2016    Second Class
4379    4380  CA-2016-140830  30/11/2016  02/12/2016    Second Class
4430    4431  CA-2017-168893  03/11/2017  08/11/2017    Second Class
4431    4432  CA-2017-168893  03/11/2017  08/11/2017    Second Class
4432    4433  CA-2017-168893  03/11/2017  08/11/2017    Second Class
4433    4434  CA-2017-168893  03/11/2017  08/11/2017    Second Class
4434    4435  CA-2017-168893  03/11/2017  08/11/2017    Second Class
4840    4841  CA-2018-154123  20/11/2018  25/11/2018  Standard Class
4879    4880  CA-2018-143567  02/11/2018  05/11/2018    Second Class
4880    4881  CA-2018-143567  02/11/2018  05/11/2018    Second Class
4881    4882  CA-2018-143567  02/11/2018  05/11/2018    Second Class
4882    4883  CA-2018-143567  02/11/2018  05/11/2018    Second Class
7090    7091  CA-2016-119480  09/01/2016  13/01/2016  Standard Class
7091    7092  CA-2016-119480  09/01/2016  13/01/2016  Standard Class
7092    7093  CA-2016-119480  09/01/2016  13/01/2016  Standard Class
7093    7094  CA-2016-119480  09/01/2016  13/01/2016  Standard Class
7114    7115  US-2017-102239  05/05/2017  06/05/2017     First Class
7115    7116  US-2017-102239  05/05/2017  06/05/2017     First Class
7474    7475  CA-2015-167199  06/01/2015  10/01/2015  Standard Class
7475    7476  CA-2015-167199  06/01/2015  10/01/2015  Standard Class
7476    7477  CA-2015-167199  06/01/2015  10/01/2015  Standard Class
7477    7478  CA-2015-167199  06/01/2015  10/01/2015  Standard Class
7478    7479  CA-2015-167199  06/01/2015  10/01/2015  Standard Class
7479    7480  CA-2015-167199  06/01/2015  10/01/2015  Standard Class
7480    7481  CA-2015-167199  06/01/2015  10/01/2015  Standard Class
8639    8640  CA-2015-129819  13/12/2015  15/12/2015    Second Class
9074    9075  CA-2015-136336  21/04/2015  26/04/2015  Standard Class
9078    9079  CA-2017-108105  16/02/2017  23/02/2017  Standard Class
9079    9080  CA-2017-108105  16/02/2017  23/02/2017  Standard Class
9273    9274  CA-2018-146983  02/09/2018  06/09/2018  Standard Class

     Customer ID     Customer Name      Segment        Country       City  \
0       CG-12520       Claire Gute     Consumer  United States  Henderson
1       CG-12520       Claire Gute     Consumer  United States  Henderson
538     DK-12985    Darren Koutras     Consumer  United States  Henderson
539     DK-12985    Darren Koutras     Consumer  United States  Henderson
996     RD-19585          Rob Dowd     Consumer  United States  Henderson
997     RD-19585          Rob Dowd     Consumer  United States  Henderson
998     RD-19585          Rob Dowd     Consumer  United States  Henderson
999     RD-19585          Rob Dowd     Consumer  United States  Henderson
1866    AH-10075         Adam Hart    Corporate  United States  Henderson
2321    KC-16255    Karen Carlisle    Corporate  United States  Henderson
2322    KC-16255    Karen Carlisle    Corporate  United States  Henderson
2323    KC-16255    Karen Carlisle    Corporate  United States  Henderson
2324    KC-16255    Karen Carlisle    Corporate  United States  Henderson
2551    AB-10105     Adrian Barton     Consumer  United States  Henderson
2552    AB-10105     Adrian Barton     Consumer  United States  Henderson
3088    DB-12910       Daniel Byrd  Home Office  United States  Henderson
3089    DB-12910       Daniel Byrd  Home Office  United States  Henderson
3537    SB-20290      Sean Braxton    Corporate  United States  Henderson
3538    SB-20290      Sean Braxton    Corporate  United States  Henderson
3539    SB-20290      Sean Braxton    Corporate  United States  Henderson
3540    SB-20290      Sean Braxton    Corporate  United States  Henderson
4378    PS-18970    Paul Stevenson  Home Office  United States  Henderson
4379    PS-18970    Paul Stevenson  Home Office  United States  Henderson
4430    AP-10915    Arthur Prichep     Consumer  United States  Henderson
4431    AP-10915    Arthur Prichep     Consumer  United States  Henderson
4432    AP-10915    Arthur Prichep     Consumer  United States  Henderson
4433    AP-10915    Arthur Prichep     Consumer  United States  Henderson
4434    AP-10915    Arthur Prichep     Consumer  United States  Henderson
4840    SC-20050  Sample Company A  Home Office  United States  Henderson
4879    TB-21175     Thomas Boland    Corporate  United States  Henderson
4880    TB-21175     Thomas Boland    Corporate  United States  Henderson
4881    TB-21175     Thomas Boland    Corporate  United States  Henderson
4882    TB-21175     Thomas Boland    Corporate  United States  Henderson
7090    CC-12685     Craig Carroll     Consumer  United States  Henderson
7091    CC-12685     Craig Carroll     Consumer  United States  Henderson
7092    CC-12685     Craig Carroll     Consumer  United States  Henderson
7093    CC-12685     Craig Carroll     Consumer  United States  Henderson
7114    LW-16990  Lindsay Williams    Corporate  United States  Henderson
7115    LW-16990  Lindsay Williams    Corporate  United States  Henderson
7474    ME-17320     Maria Etezadi  Home Office  United States  Henderson
7475    ME-17320     Maria Etezadi  Home Office  United States  Henderson
7476    ME-17320     Maria Etezadi  Home Office  United States  Henderson
7477    ME-17320     Maria Etezadi  Home Office  United States  Henderson
7478    ME-17320     Maria Etezadi  Home Office  United States  Henderson
7479    ME-17320     Maria Etezadi  Home Office  United States  Henderson
7480    ME-17320     Maria Etezadi  Home Office  United States  Henderson
8639    KC-16675   Kimberly Carter    Corporate  United States  Henderson
9074    DB-13555   Dorothy Badders    Corporate  United States  Henderson
9078    GW-14605  Giulietta Weimer     Consumer  United States  Henderson
9079    GW-14605  Giulietta Weimer     Consumer  United States  Henderson
9273    AH-10210        Alan Hwang     Consumer  United States  Henderson

         State  Postal Code Region       Product ID         Category  \
0     Kentucky      42420.0  South  FUR-BO-10001798        Furniture
1     Kentucky      42420.0  South  FUR-CH-10000454        Furniture
538   Kentucky      42420.0  South  OFF-AP-10001271  Office Supplies
539   Kentucky      42420.0  South  FUR-CH-10002647        Furniture
996   Kentucky      42420.0  South  OFF-EN-10003862  Office Supplies
997   Kentucky      42420.0  South  OFF-ST-10004258  Office Supplies
998   Kentucky      42420.0  South  FUR-FU-10002885        Furniture
999   Kentucky      42420.0  South  FUR-FU-10001918        Furniture
1866    Nevada      89015.0   West  FUR-FU-10004460        Furniture
2321  Kentucky      42420.0  South  OFF-BI-10004492  Office Supplies
2322  Kentucky      42420.0  South  OFF-BI-10001072  Office Supplies
2323  Kentucky      42420.0  South  OFF-BI-10003707  Office Supplies
2324  Kentucky      42420.0  South  OFF-BI-10000977  Office Supplies
2551  Kentucky      42420.0  South  FUR-FU-10004665        Furniture
2552  Kentucky      42420.0  South  OFF-BI-10000088  Office Supplies
3088  Kentucky      42420.0  South  FUR-FU-10001591        Furniture
3089  Kentucky      42420.0  South  TEC-PH-10000526       Technology
3537  Kentucky      42420.0  South  OFF-ST-10000107  Office Supplies
3538  Kentucky      42420.0  South  OFF-LA-10001641  Office Supplies
3539  Kentucky      42420.0  South  OFF-LA-10003121  Office Supplies
3540  Kentucky      42420.0  South  OFF-PA-10002689  Office Supplies
4378  Kentucky      42420.0  South  OFF-EN-10000461  Office Supplies
4379  Kentucky      42420.0  South  OFF-EN-10002831  Office Supplies
4430  Kentucky      42420.0  South  OFF-FA-10002280  Office Supplies
4431  Kentucky      42420.0  South  OFF-AR-10001770  Office Supplies
4432  Kentucky      42420.0  South  FUR-FU-10002885        Furniture
4433  Kentucky      42420.0  South  OFF-AR-10003772  Office Supplies
4434  Kentucky      42420.0  South  FUR-TA-10003392        Furniture
4840  Kentucky      42420.0  South  FUR-FU-10000629        Furniture
4879  Kentucky      42420.0  South  OFF-EN-10004846  Office Supplies
4880  Kentucky      42420.0  South  FUR-CH-10000454        Furniture
4881  Kentucky      42420.0  South  TEC-AC-10004145       Technology
4882  Kentucky      42420.0  South  OFF-ST-10001580  Office Supplies
7090  Kentucky      42420.0  South  OFF-PA-10000474  Office Supplies
7091  Kentucky      42420.0  South  OFF-AP-10001205  Office Supplies
7092  Kentucky      42420.0  South  OFF-AR-10004691  Office Supplies
7093  Kentucky      42420.0  South  OFF-PA-10004996  Office Supplies
7114    Nevada      89015.0   West  FUR-TA-10003392        Furniture
7115    Nevada      89015.0   West  OFF-BI-10001890  Office Supplies
7474  Kentucky      42420.0  South  FUR-CH-10004063        Furniture
7475  Kentucky      42420.0  South  OFF-BI-10004632  Office Supplies
7476  Kentucky      42420.0  South  OFF-AR-10001662  Office Supplies
7477  Kentucky      42420.0  South  TEC-PH-10004977       Technology
7478  Kentucky      42420.0  South  TEC-PH-10004539       Technology
7479  Kentucky      42420.0  South  OFF-FA-10001883  Office Supplies
7480  Kentucky      42420.0  South  OFF-PA-10000955  Office Supplies
8639  Kentucky      42420.0  South  OFF-BI-10004970  Office Supplies
9074  Kentucky      42420.0  South  OFF-ST-10002574  Office Supplies
9078  Kentucky      42420.0  South  FUR-FU-10003773        Furniture
9079  Kentucky      42420.0  South  OFF-BI-10002412  Office Supplies
9273  Kentucky      42420.0  South  OFF-BI-10003650  Office Supplies

     Sub-Category                                       Product Name     Sales
0       Bookcases                  Bush Somerset Collection Bookcase   261.960
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...   731.940
538    Appliances    Eureka The Boss Cordless Rechargeable Stick Vac   152.940
539        Chairs         Situations Contoured Folding Chairs, 4/Set   283.920
996     Envelopes                 Laser & Ink Jet Business Envelopes    10.670
997       Storage                         Portable Personal File Box    36.630
998   Furnishings              Magna Visual Magnetic Picture Hangers    24.100
999   Furnishings  C-Line Cubicle Keepers Polyproplyene Holder Wi...    33.110
1866  Furnishings                 Howard Miller 12" Round Wall Clock   196.450
2321      Binders                                    Tuf-Vin Binders    94.740
2322      Binders  GBC Clear Cover, 8-1/2 x 11, unpunched, 25 cov...    60.640
2323      Binders                               Aluminum Screw Posts    76.300
2324      Binders                 Ibico Plastic Spiral Binding Combs   364.800
2551  Furnishings  3M Polarizing Task Lamp with Clamp Arm, Light ...   821.880
2552      Binders                             GBC Imprintable Covers    21.960
3088  Furnishings    Advantus Panel Wall Certificate Holder - 8.5x11    61.000
3089       Phones                                       Vtech CS6719   671.930
3537      Storage                         Fellowes Super Stor/Drawer    83.250
3538       Labels                                          Avery 518     9.450
3539       Labels                                          Avery 506    20.650
3540        Paper  Weyerhaeuser First Choice Laser/Copy Paper (20...    45.360
4378    Envelopes            #10- 4 1/8" x 9 1/2" Recycled Envelopes    17.480
4379    Envelopes    Tyvek  Top-Opening Peel & Seel  Envelopes, Gray    71.880
4430    Fasteners                       Advantus Plastic Paper Clips    20.000
4431          Art                                 Economy #2 Pencils     7.980
4432  Furnishings              Magna Visual Magnetic Picture Hangers    24.100
4433          Art  Boston 16750 Black Compact Battery Pencil Shar...     8.750
4434       Tables            Global Adaptabilities Conference Tables   842.940
4840  Furnishings                    9-3/4 Diameter Round Wall Clock    27.580
4879    Envelopes  Letter or Legal Size Expandable Poly String Ti...     5.320
4880       Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...   975.920
4881  Accessories                      Logitech diNovo Edge Keyboard  2249.910
4882      Storage              Super Decoflex Portable Personal File    59.920
7090        Paper                                  Easy-staple paper   106.320
7091   Appliances          Belkin 5 Outlet SurgeMaster Power Centers   163.440
7092          Art      Boston 1730 StandUp Electric Pencil Sharpener    42.760
7093        Paper       Speediset Carbonless Redi-Letter 7" x 8 1/2"    51.550
7114       Tables            Global Adaptabilities Conference Tables  1685.880
7115      Binders                          Avery Poly Binder Pockets     5.728
7474       Chairs            Global Deluxe High-Back Manager's Chair  2573.820
7475      Binders                Ibico Hi-Tech Manual Binding System   609.980
7476          Art            Rogers Handheld Barrel Pencil Sharpener     5.480
7477       Phones                                        GE 30524EE4   391.980
7478       Phones  Wireless Extenders zBoost YX545 SOHO Signal Bo...   755.960
7479    Fasteners          Alliance Super-Size Bands, Assorted Sizes    31.120
7480        Paper    Southworth 25% Cotton Granite Paper & Envelopes     6.540
8639      Binders                   ACCOHIDE 3-Ring Binder, Blue, 1"    12.390
9074      Storage              SAFCO Commercial Wire Shelving, Black   828.840
9078  Furnishings  Eldon Cleatmat Plus Chair Mats for High Pile C...   318.080
9079      Binders  Wilson Jones “Snap” Scratch Pad Binder Tool fo...     5.800
9273      Binders          GBC DocuBind 300 Electric Binding Machine  1577.940

In [ ]:
# Updating Values:
df.loc[1,["Country", "Region"]] = ["Pakistan", "East"]
print(df)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2017-152156  08/11/2017  11/11/2017    Second Class
1          2  CA-2017-152156  08/11/2017  11/11/2017    Second Class
2          3  CA-2017-138688  12/06/2017  16/06/2017    Second Class
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class
4          5  US-2016-108966  11/10/2016  18/10/2016  Standard Class
...      ...             ...         ...         ...             ...
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer       Pakistan        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo

           State  Postal Code   Region       Product ID         Category  \
0       Kentucky      42420.0    South  FUR-BO-10001798        Furniture
1       Kentucky      42420.0     East  FUR-CH-10000454        Furniture
2     California      90036.0     West  OFF-LA-10000240  Office Supplies
3        Florida      33311.0    South  FUR-TA-10000577        Furniture
4        Florida      33311.0    South  OFF-ST-10000760  Office Supplies
...          ...          ...      ...              ...              ...
9795    Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies
9796        Ohio      43615.0     East  OFF-AR-10001374  Office Supplies
9797        Ohio      43615.0     East  TEC-PH-10004977       Technology
9798        Ohio      43615.0     East  TEC-PH-10000912       Technology
9799        Ohio      43615.0     East  TEC-AC-10000487       Technology

     Sub-Category                                       Product Name     Sales
0       Bookcases                  Bush Somerset Collection Bookcase  261.9600
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2          Labels  Self-Adhesive Address Labels for Typewriters b...   14.6200
3          Tables      Bretford CR4500 Series Slim Rectangular Table  957.5775
4         Storage                     Eldon Fold 'N Roll Cart System   22.3680
...           ...                                                ...       ...
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.7980
9796          Art           BIC Brite Liner Highlighters, Chisel Tip   10.3680
9797       Phones                                        GE 30524EE4  235.1880
9798       Phones           Anker 24W Portable Micro USB Car Charger   26.3760
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive   10.3840

[9800 rows x 18 columns]

In [ ]:
# Deleting Rows and Columns:
# Delete a Column:
df = df.drop("Category", axis = 1)
print(df)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2017-152156  08/11/2017  11/11/2017    Second Class
1          2  CA-2017-152156  08/11/2017  11/11/2017    Second Class
2          3  CA-2017-138688  12/06/2017  16/06/2017    Second Class
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class
4          5  US-2016-108966  11/10/2016  18/10/2016  Standard Class
...      ...             ...         ...         ...             ...
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer       Pakistan        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo

           State       Product ID Sub-Category  \
0       Kentucky  FUR-BO-10001798    Bookcases
1       Kentucky  FUR-CH-10000454       Chairs
2     California  OFF-LA-10000240       Labels
3        Florida  FUR-TA-10000577       Tables
4        Florida  OFF-ST-10000760      Storage
...          ...              ...          ...
9795    Illinois  OFF-BI-10003429      Binders
9796        Ohio  OFF-AR-10001374          Art
9797        Ohio  TEC-PH-10004977       Phones
9798        Ohio  TEC-PH-10000912       Phones
9799        Ohio  TEC-AC-10000487  Accessories

                                           Product Name     Sales
0                     Bush Somerset Collection Bookcase  261.9600
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2     Self-Adhesive Address Labels for Typewriters b...   14.6200
3         Bretford CR4500 Series Slim Rectangular Table  957.5775
4                        Eldon Fold 'N Roll Cart System   22.3680
...                                                 ...       ...
9795  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.7980
9796           BIC Brite Liner Highlighters, Chisel Tip   10.3680
9797                                        GE 30524EE4  235.1880
9798           Anker 24W Portable Micro USB Car Charger   26.3760
9799                SanDisk Cruzer 4 GB USB Flash Drive   10.3840

[9800 rows x 15 columns]

In [ ]:
# Delete a Row:
df = df.drop(4, axis = 0)
print(df)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
2          3  CA-2017-138688  12/06/2017  16/06/2017    Second Class
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class
5          6  CA-2015-115812  09/06/2015  14/06/2015  Standard Class
6          7  CA-2015-115812  09/06/2015  14/06/2015  Standard Class
7          8  CA-2015-115812  09/06/2015  14/06/2015  Standard Class
...      ...             ...         ...         ...             ...
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country             City  \
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
5       BH-11710   Brosina Hoffman   Consumer  United States      Los Angeles
6       BH-11710   Brosina Hoffman   Consumer  United States      Los Angeles
7       BH-11710   Brosina Hoffman   Consumer  United States      Los Angeles
...          ...               ...        ...            ...              ...
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo

           State       Product ID Sub-Category  \
2     California  OFF-LA-10000240       Labels
3        Florida  FUR-TA-10000577       Tables
5     California  FUR-FU-10001487  Furnishings
6     California  OFF-AR-10002833          Art
7     California  TEC-PH-10002275       Phones
...          ...              ...          ...
9795    Illinois  OFF-BI-10003429      Binders
9796        Ohio  OFF-AR-10001374          Art
9797        Ohio  TEC-PH-10004977       Phones
9798        Ohio  TEC-PH-10000912       Phones
9799        Ohio  TEC-AC-10000487  Accessories

                                           Product Name     Sales
2     Self-Adhesive Address Labels for Typewriters b...   14.6200
3         Bretford CR4500 Series Slim Rectangular Table  957.5775
5     Eldon Expressions Wood and Plastic Desk Access...   48.8600
6                                            Newell 322    7.2800
7                        Mitel 5320 IP Phone VoIP phone  907.1520
...                                                 ...       ...
9795  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.7980
9796           BIC Brite Liner Highlighters, Chisel Tip   10.3680
9797                                        GE 30524EE4  235.1880
9798           Anker 24W Portable Micro USB Car Charger   26.3760
9799                SanDisk Cruzer 4 GB USB Flash Drive   10.3840

[9797 rows x 15 columns]

In [ ]:
# Handling Missing Values:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Product ID       0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [ ]:
# Remove Missing Values:
df.dropna()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Product ID,Sub-Category,Product Name,Sales
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,OFF-LA-10000240,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,FUR-TA-10000577,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
5,6,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,FUR-FU-10001487,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600
6,7,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,OFF-AR-10002833,Art,Newell 322,7.2800
7,8,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,TEC-PH-10002275,Phones,Mitel 5320 IP Phone VoIP phone,907.1520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,OFF-BI-10003429,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,OFF-AR-10001374,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,TEC-PH-10004977,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,TEC-PH-10000912,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,TEC-AC-10000487,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [ ]:
# Fill Missing Values:
df["Sales"] = df["Sales"].fillna(df["Sales"].mean())
print(df)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
2          3  CA-2017-138688  12/06/2017  16/06/2017    Second Class
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class
5          6  CA-2015-115812  09/06/2015  14/06/2015  Standard Class
6          7  CA-2015-115812  09/06/2015  14/06/2015  Standard Class
7          8  CA-2015-115812  09/06/2015  14/06/2015  Standard Class
...      ...             ...         ...         ...             ...
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country             City  \
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
5       BH-11710   Brosina Hoffman   Consumer  United States      Los Angeles
6       BH-11710   Brosina Hoffman   Consumer  United States      Los Angeles
7       BH-11710   Brosina Hoffman   Consumer  United States      Los Angeles
...          ...               ...        ...            ...              ...
9795    SH-19975     Sally Hughsby  Corporate  United States          Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States           Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States           Toledo

           State       Product ID Sub-Category  \
2     California  OFF-LA-10000240       Labels
3        Florida  FUR-TA-10000577       Tables
5     California  FUR-FU-10001487  Furnishings
6     California  OFF-AR-10002833          Art
7     California  TEC-PH-10002275       Phones
...          ...              ...          ...
9795    Illinois  OFF-BI-10003429      Binders
9796        Ohio  OFF-AR-10001374          Art
9797        Ohio  TEC-PH-10004977       Phones
9798        Ohio  TEC-PH-10000912       Phones
9799        Ohio  TEC-AC-10000487  Accessories

                                           Product Name     Sales
2     Self-Adhesive Address Labels for Typewriters b...   14.6200
3         Bretford CR4500 Series Slim Rectangular Table  957.5775
5     Eldon Expressions Wood and Plastic Desk Access...   48.8600
6                                            Newell 322    7.2800
7                        Mitel 5320 IP Phone VoIP phone  907.1520
...                                                 ...       ...
9795  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.7980
9796           BIC Brite Liner Highlighters, Chisel Tip   10.3680
9797                                        GE 30524EE4  235.1880
9798           Anker 24W Portable Micro USB Car Charger   26.3760
9799                SanDisk Cruzer 4 GB USB Flash Drive   10.3840

[9797 rows x 15 columns]

In [ ]:
# Handling Duplicate Data:
print(df.duplicated())

2       False
3       False
5       False
6       False
7       False
        ...
9795    False
9796    False
9797    False
9798    False
9799    False
Length: 9797, dtype: bool

In [ ]:
# Sorting Data:
df = (df.sort_values("Sales", ascending = True))
print(df)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
4101    4102  US-2018-102288  19/06/2018  23/06/2018  Standard Class
9292    9293  CA-2018-124114  02/03/2018  02/03/2018        Same Day
8658    8659  CA-2017-168361  21/06/2017  25/06/2017  Standard Class
4711    4712  CA-2015-112403  31/03/2015  31/03/2015        Same Day
2106    2107  US-2015-152723  26/09/2015  26/09/2015        Same Day
...      ...             ...         ...         ...             ...
4190    4191  CA-2018-166709  17/11/2018  22/11/2018  Standard Class
2623    2624  CA-2018-127180  22/10/2018  24/10/2018     First Class
8153    8154  CA-2018-140151  23/03/2018  25/03/2018     First Class
6826    6827  CA-2017-118689  02/10/2017  09/10/2017  Standard Class
2697    2698  CA-2015-145317  18/03/2015  23/03/2015  Standard Class

     Customer ID     Customer Name      Segment        Country           City  \
4101    ZC-21910  Zuschuss Carroll     Consumer  United States        Houston
9292    RS-19765    Roland Schwarz    Corporate  United States           Waco
8658    KB-16600       Ken Brennan    Corporate  United States        Chicago
4711    JO-15280     Jas O'Carroll     Consumer  United States   Philadelphia
2106    HG-14965     Henry Goldwyn    Corporate  United States       Mesquite
...          ...               ...          ...            ...            ...
4190    HL-15040      Hunter Lopez     Consumer  United States         Newark
2623    TA-21385      Tom Ashbrook  Home Office  United States  New York City
8153    RB-19360      Raymond Buch     Consumer  United States        Seattle
6826    TC-20980      Tamara Chand    Corporate  United States      Lafayette
2697    SM-20320       Sean Miller  Home Office  United States   Jacksonville

             State       Product ID Sub-Category  \
4101         Texas  OFF-AP-10002906   Appliances
9292         Texas  OFF-BI-10004022      Binders
8658      Illinois  OFF-BI-10003727      Binders
4711  Pennsylvania  OFF-BI-10003529      Binders
2106         Texas  OFF-BI-10003460      Binders
...            ...              ...          ...
4190      Delaware  TEC-CO-10004722      Copiers
2623      New York  TEC-CO-10004722      Copiers
8153    Washington  TEC-CO-10004722      Copiers
6826       Indiana  TEC-CO-10004722      Copiers
2697       Florida  TEC-MA-10002412     Machines

                                           Product Name      Sales
4101  Hoover Replacement Belt for Commercial Guardsm...      0.444
9292           Acco Suede Grain Vinyl Round Ring Binder      0.556
8658  Avery Durable Slant Ring Binders With Label Ho...      0.836
4711                      Avery Round Ring Poly Binders      0.852
2106                                  Acco 3-Hole Punch      0.876
...                                                 ...        ...
4190              Canon imageCLASS 2200 Advanced Copier  10499.970
2623              Canon imageCLASS 2200 Advanced Copier  11199.968
8153              Canon imageCLASS 2200 Advanced Copier  13999.960
6826              Canon imageCLASS 2200 Advanced Copier  17499.950
2697  Cisco TelePresence System EX90 Videoconferenci...  22638.480

[9797 rows x 15 columns]

In [ ]:
# from lowest to highest:
# Sorting Data:
df = (df.sort_values("Sales", ascending = False))
print(df)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
2697    2698  CA-2015-145317  18/03/2015  23/03/2015  Standard Class
6826    6827  CA-2017-118689  02/10/2017  09/10/2017  Standard Class
8153    8154  CA-2018-140151  23/03/2018  25/03/2018     First Class
2623    2624  CA-2018-127180  22/10/2018  24/10/2018     First Class
4190    4191  CA-2018-166709  17/11/2018  22/11/2018  Standard Class
...      ...             ...         ...         ...             ...
2106    2107  US-2015-152723  26/09/2015  26/09/2015        Same Day
4711    4712  CA-2015-112403  31/03/2015  31/03/2015        Same Day
8658    8659  CA-2017-168361  21/06/2017  25/06/2017  Standard Class
9292    9293  CA-2018-124114  02/03/2018  02/03/2018        Same Day
4101    4102  US-2018-102288  19/06/2018  23/06/2018  Standard Class

     Customer ID     Customer Name      Segment        Country           City  \
2697    SM-20320       Sean Miller  Home Office  United States   Jacksonville
6826    TC-20980      Tamara Chand    Corporate  United States      Lafayette
8153    RB-19360      Raymond Buch     Consumer  United States        Seattle
2623    TA-21385      Tom Ashbrook  Home Office  United States  New York City
4190    HL-15040      Hunter Lopez     Consumer  United States         Newark
...          ...               ...          ...            ...            ...
2106    HG-14965     Henry Goldwyn    Corporate  United States       Mesquite
4711    JO-15280     Jas O'Carroll     Consumer  United States   Philadelphia
8658    KB-16600       Ken Brennan    Corporate  United States        Chicago
9292    RS-19765    Roland Schwarz    Corporate  United States           Waco
4101    ZC-21910  Zuschuss Carroll     Consumer  United States        Houston

             State       Product ID Sub-Category  \
2697       Florida  TEC-MA-10002412     Machines
6826       Indiana  TEC-CO-10004722      Copiers
8153    Washington  TEC-CO-10004722      Copiers
2623      New York  TEC-CO-10004722      Copiers
4190      Delaware  TEC-CO-10004722      Copiers
...            ...              ...          ...
2106         Texas  OFF-BI-10003460      Binders
4711  Pennsylvania  OFF-BI-10003529      Binders
8658      Illinois  OFF-BI-10003727      Binders
9292         Texas  OFF-BI-10004022      Binders
4101         Texas  OFF-AP-10002906   Appliances

                                           Product Name      Sales
2697  Cisco TelePresence System EX90 Videoconferenci...  22638.480
6826              Canon imageCLASS 2200 Advanced Copier  17499.950
8153              Canon imageCLASS 2200 Advanced Copier  13999.960
2623              Canon imageCLASS 2200 Advanced Copier  11199.968
4190              Canon imageCLASS 2200 Advanced Copier  10499.970
...                                                 ...        ...
2106                                  Acco 3-Hole Punch      0.876
4711                      Avery Round Ring Poly Binders      0.852
8658  Avery Durable Slant Ring Binders With Label Ho...      0.836
9292           Acco Suede Grain Vinyl Round Ring Binder      0.556
4101  Hoover Replacement Belt for Commercial Guardsm...      0.444

[9797 rows x 15 columns]

In [ ]:
# Aggregation:
# Sum:
df["Sales"].sum()

np.float64(230.73599210982957)

In [ ]:
# Average:
df["Sales"].mean()

np.float64(230.73599210982957)

In [ ]:
# Maximum:
df["Sales"].max()

22638.48

In [ ]:
# Minimum:
df["Sales"].min()

0.444

In [ ]:
df["Sales"].count()

np.int64(9797)

In [ ]:
# groupby():
df.groupby("State")["Sales"].sum()

State
Alabama                  19510.6400
Arizona                  35272.6570
Arkansas                 11678.1300
California              446306.4635
Colorado                 31841.5980
Connecticut              13384.3570
Delaware                 27322.9990
District of Columbia      2865.0200
Florida                  88414.1640
Georgia                  48219.1100
Idaho                     4382.4860
Illinois                 79236.5170
Indiana                  48718.4000
Iowa                      4443.5600
Kansas                    2914.3100
Kentucky                 35464.4900
Louisiana                 9131.0500
Maine                     1270.5300
Maryland                 23705.5230
Massachusetts            28634.4340
Michigan                 76136.0740
Minnesota                29863.1500
Mississippi              10771.3400
Missouri                 22205.1500
Montana                   5589.3520
Nebraska                  7464.9300
Nevada                   16729.1020
New Hampshire             7292.5240
New Jersey               34610.9720
New Mexico                4783.5220
New York                306361.1470
North Carolina           55165.9640
North Dakota               919.9100
Ohio                     75130.3500
Oklahoma                 19683.3900
Oregon                   17284.4620
Pennsylvania            116276.6500
Rhode Island             22525.0260
South Carolina            8481.7100
South Dakota              1315.5600
Tennessee                30661.8730
Texas                   168572.5322
Utah                     11220.0560
Vermont                   8929.3700
Virginia                 70636.7200
Washington              135206.8500
West Virginia             1209.8240
Wisconsin                31173.4300
Wyoming                   1603.1360
Name: Sales, dtype: float64

In [ ]:
df.groupby("State")["Sales"].mean()

State
Alabama                  319.846557
Arizona                  158.173350
Arkansas                 194.635500
California               229.345562
Colorado                 177.886022
Connecticut              163.223866
Delaware                 293.795688
District of Columbia     286.502000
Florida                  237.672484
Georgia                  272.424350
Idaho                    208.689810
Illinois                 164.050760
Indiana                  360.877037
Iowa                     170.906154
Kansas                   121.429583
Kentucky                 262.699926
Louisiana                222.708537
Maine                    158.816250
Maryland                 225.766886
Massachusetts            212.106919
Michigan                 300.933099
Minnesota                335.541011
Mississippi              203.232830
Missouri                 336.441667
Montana                  372.623467
Nebraska                 196.445526
Nevada                   428.951333
New Hampshire            270.093481
New Jersey               283.696492
New Mexico               129.284378
New York                 279.271784
North Carolina           223.343984
North Dakota             131.415714
Ohio                     165.485352
Oklahoma                 298.233182
Oregon                   141.675918
Pennsylvania             199.788058
Rhode Island             409.545927
South Carolina           201.945476
South Dakota             109.630000
Tennessee                167.551219
Texas                    173.250290
Utah                     211.699170
Vermont                  811.760909
Virginia                 315.342500
Washington               268.267560
West Virginia            302.456000
Wisconsin                296.889810
Wyoming                 1603.136000
Name: Sales, dtype: float64

In [ ]:
# Concat:
df1 = {
    "Customer Name" : ["Ali", "Sara", "Ahmed", "Zaid"],
    "City" : ["Karachi", "Islamabad", "Karachi", "Lahore"]
}
df2 = {
    "Customer Name" : ["Ahad", "Saira", "Ayesha", "Zahid"],
    "City" : ["Karachi", "Islamabad", "Multan", "Lahore"]
}
df1 = pd.DataFrame(df1)
df2 = pd.DataFrame(df2)
final_result = pd.concat([df1, df2], ignore_index=True)
print(final_result)

  Customer Name       City
0           Ali    Karachi
1          Sara  Islamabad
2         Ahmed    Karachi
3          Zaid     Lahore
4          Ahad    Karachi
5         Saira  Islamabad
6        Ayesha     Multan
7         Zahid     Lahore

In [ ]:
# Merge:
Employees = pd.DataFrame({
    "ID": [1, 2, 3],
    "Employee": ["Ayan", "Sana", "Aisha"]
})

Salary = pd.DataFrame({
    "ID": [1, 2, 3],
    "Salary": [8000, 9000, 7000]
})
final_df = pd.merge(Employees, Salary, on="ID")

print(final_df)

   ID Employee  Salary
0   1     Ayan    8000
1   2     Sana    9000
2   3    Aisha    7000